/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BinaryFileManagerPlugin
});
module.exports = __toCommonJS(main_exports);

// src/Extension.ts
var FileExtensionManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.extensions = new Set(this.plugin.settings.extensions);
  }
  getExtensionMatchedBest(filename) {
    for (let id = 0; id < filename.length; id++) {
      if (filename[id] !== ".") {
        continue;
      }
      const ext = filename.slice(id).replace(/^\./, "");
      if (ext === "") {
        return void 0;
      }
      if (this.extensions.has(ext)) {
        return ext;
      }
    }
    return void 0;
  }
  add(ext) {
    this.extensions.add(ext);
  }
  delete(ext) {
    this.extensions.delete(ext);
  }
  has(ext) {
    return this.extensions.has(ext);
  }
  verify(filepath) {
    for (const ext of this.extensions) {
      if (filepath.endsWith(`.${ext}`)) {
        return true;
      }
    }
    return false;
  }
  toArray() {
    return Array.from(this.extensions);
  }
};

// src/FileList.ts
var import_obsidian = require("obsidian");
var PLUGIN_NAME = "obsidian-binary-file-manager-plugin";
var REGISTERED_BINARY_FILE_STORAGE_FILE_NAME = ".binary-file-manager_binary-file-list.txt";
var FileListAdapter = class {
  constructor(app, _plugin) {
    this.app = app;
    this.registeredBinaryFilePaths = /* @__PURE__ */ new Set();
    this.app.workspace.onLayoutReady(() => __async(this, null, function* () {
      this.deleteNonExistingBinaryFiles();
    }));
  }
  load() {
    return __async(this, null, function* () {
      yield this.loadBinaryFiles();
      return this;
    });
  }
  save() {
    return __async(this, null, function* () {
      yield this.saveBinaryFiles();
    });
  }
  add(filepath) {
    this.registeredBinaryFilePaths.add(filepath);
  }
  delete(filepath) {
    this.registeredBinaryFilePaths.delete(filepath);
  }
  has(filepath) {
    return this.registeredBinaryFilePaths.has(filepath);
  }
  deleteAll() {
    this.registeredBinaryFilePaths = /* @__PURE__ */ new Set();
  }
  loadBinaryFiles() {
    return __async(this, null, function* () {
      const configDir = this.app.vault.configDir;
      const storageFilePath = (0, import_obsidian.normalizePath)(
        `${configDir}/plugins/${PLUGIN_NAME}/${REGISTERED_BINARY_FILE_STORAGE_FILE_NAME}`
      );
      if (!(yield this.app.vault.adapter.exists(storageFilePath))) {
        this.registeredBinaryFilePaths = /* @__PURE__ */ new Set();
        return;
      }
      const binaryFiles = (yield this.app.vault.adapter.read(storageFilePath)).trim().split(/\r?\n/);
      this.registeredBinaryFilePaths = new Set(binaryFiles);
    });
  }
  saveBinaryFiles() {
    return __async(this, null, function* () {
      const configDir = this.app.vault.configDir;
      const storageFilePath = (0, import_obsidian.normalizePath)(
        `${configDir}/plugins/${PLUGIN_NAME}/${REGISTERED_BINARY_FILE_STORAGE_FILE_NAME}`
      );
      yield this.app.vault.adapter.write(
        storageFilePath,
        Array.from(this.registeredBinaryFilePaths).join("\n")
      );
    });
  }
  deleteNonExistingBinaryFiles() {
    return __async(this, null, function* () {
      const difference = new Set(this.registeredBinaryFilePaths);
      for (const file of this.app.vault.getFiles()) {
        difference.delete(file.path);
      }
      for (const fileToBeUnregistered of difference) {
        this.registeredBinaryFilePaths.delete(fileToBeUnregistered);
      }
      yield this.saveBinaryFiles();
    });
  }
};

// src/Formatter.ts
var import_obsidian2 = require("obsidian");
var DATE_REGEXP = /{{CDATE:([^}\n\r]*)}}/g;
var NAME_REGEX = /{{NAME(((:UP)|(:LOW))?)}}/g;
var FULLNAME_REGEX = /{{FULLNAME(((:UP)|(:LOW))?)}}/g;
var EXTENSION_REGEX = /{{EXTENSION(((:UP)|(:LOW))?)}}/g;
var PATH_REGEX = /{{PATH(((:UP)|(:LOW))?)}}/g;
var NOW_REGEXP = /{{NOW:([^}\n\r]*)}}/g;
var LINK_SYNTAX = "{{LINK}}";
var EMBED_SYNTAX = "{{EMBED}}";
var Formatter = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  format(input, filepath, createdAt) {
    var _a;
    let output = input;
    output = this.replaceDate(output, createdAt);
    output = this.replaceNow(output);
    const fullname = basename(filepath);
    const extension = (_a = this.plugin.fileExtensionManager.getExtensionMatchedBest(fullname)) != null ? _a : "";
    const nameWithoutExtension = basename(fullname, extension);
    output = this.replacePath(output, filepath);
    output = this.replaceFullName(output, fullname);
    output = this.replaceName(output, nameWithoutExtension);
    output = this.replaceExtension(output, extension);
    output = this.replaceLink(output, filepath);
    output = this.replaceEmbed(output, filepath);
    return output;
  }
  replaceDate(input, unixMilliSecond) {
    const output = input.replace(
      DATE_REGEXP,
      (_matched, fmt) => {
        return (0, import_obsidian2.moment)(unixMilliSecond).format(fmt);
      }
    );
    return output;
  }
  replaceFullName(input, fullname) {
    return input.replace(
      FULLNAME_REGEX,
      (_matched, caseMode) => {
        if (!caseMode) {
          return fullname;
        } else if (caseMode === ":UP") {
          return fullname.toUpperCase();
        } else {
          return fullname.toLowerCase();
        }
      }
    );
  }
  replaceName(input, filename) {
    return input.replace(
      NAME_REGEX,
      (_matched, caseMode) => {
        if (!caseMode) {
          return filename;
        } else if (caseMode === ":UP") {
          return filename.toUpperCase();
        } else {
          return filename.toLowerCase();
        }
      }
    );
  }
  replaceExtension(input, extension) {
    return input.replace(
      EXTENSION_REGEX,
      (_matched, caseMode) => {
        if (!caseMode) {
          return extension;
        } else if (caseMode === ":UP") {
          return extension.toUpperCase();
        } else {
          return extension.toLowerCase();
        }
      }
    );
  }
  replaceNow(input) {
    const currentDate = (0, import_obsidian2.moment)();
    return input.replace(
      NOW_REGEXP,
      (_matched, fmt) => {
        return currentDate.format(fmt);
      }
    );
  }
  replacePath(input, filepath) {
    return input.replace(
      PATH_REGEX,
      (_matched, caseMode) => {
        if (!caseMode) {
          return filepath;
        } else if (caseMode === ":UP") {
          return filepath.toUpperCase();
        } else {
          return filepath.toLowerCase();
        }
      }
    );
  }
  replaceLink(input, filepath) {
    return input.replace(LINK_SYNTAX, `[[${filepath}]]`);
  }
  replaceEmbed(input, filepath) {
    return input.replace(EMBED_SYNTAX, `![[${filepath}]]`);
  }
};
function cleanPath(filepath) {
  let cleanedPath = filepath;
  cleanedPath = cleanedPath.replace(/\\/g, "/");
  if (cleanedPath === "") {
    cleanedPath = "/";
  }
  for (let i = 0; i < cleanedPath.length; i++) {
    if (cleanedPath[i] !== "/") {
      cleanedPath = cleanedPath.substring(i);
      break;
    } else if (i === cleanedPath.length - 1) {
      cleanedPath = "/";
      break;
    }
  }
  for (let i = cleanedPath.length - 1; i >= 0; i--) {
    if (cleanedPath[i] !== "/") {
      break;
    } else if (i === 0) {
      cleanedPath = "/";
      break;
    }
  }
  return cleanedPath;
}
function basename(filepath, extension) {
  var _a;
  const segments = cleanPath(filepath).split("/");
  const filename = (_a = segments.last()) != null ? _a : "";
  const ext = extension != null ? extension : "";
  return filename.replace(new RegExp(`\\.${ext}$`), "");
}

// src/Util.ts
function retry(callback, timeoutMilliSecond, trials, check = (_) => true) {
  return __async(this, null, function* () {
    if (!Number.isInteger(trials)) {
      throw `arg trials: ${trials} is not an integer
		`;
    }
    const result = yield Promise.race([
      delay(timeoutMilliSecond),
      (() => __async(null, null, function* () {
        for (let i = 0; i < trials; i++) {
          const t = callback();
          if (t !== void 0 && check(t)) {
            return t;
          }
          yield delay(1);
        }
        return void 0;
      }))()
    ]);
    if (result === void 0) {
      return void 0;
    }
    return result;
  });
}
function delay(milliSecond) {
  return __async(this, null, function* () {
    yield new Promise((resolve) => setTimeout(resolve, milliSecond));
    return void 0;
  });
}
var INVALID_CHARS_IN_FILE_NAME = /* @__PURE__ */ new Set([
  "\\",
  "/",
  ":",
  "*",
  "?",
  '"',
  "<",
  ">",
  "|"
]);
function validFileName(fileName) {
  for (const char of fileName) {
    if (INVALID_CHARS_IN_FILE_NAME.has(char)) {
      return { valid: false, included: char };
    }
  }
  return { valid: true };
}

// src/Generator.ts
var import_obsidian3 = require("obsidian");
var TEMPLATER_PLUGIN_NAME = "templater-obsidian";
var DEFAULT_TEMPLATE_CONTENT = `![[{{PATH}}]]
LINK: [[{{PATH}}]]
CREATED At: {{CDATE:YYYY-MM-DD}}
FILE TYPE: {{EXTENSION:UP}}
`;
var RETRY_NUMBER = 1e3;
var TIMEOUT_MILLISECOND = 1e3;
var MetaDataGenerator = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  shouldCreateMetaDataFile(file) {
    return __async(this, null, function* () {
      if (!(file instanceof import_obsidian3.TFile)) {
        return false;
      }
      const matchedExtension = this.plugin.fileExtensionManager.getExtensionMatchedBest(file.name);
      if (!matchedExtension) {
        return false;
      }
      if (this.plugin.fileListAdapter.has(file.path)) {
        return false;
      }
      return true;
    });
  }
  create(file) {
    return __async(this, null, function* () {
      const metaDataFileName = this.uniquefyMetaDataFileName(
        this.generateMetaDataFileName(file)
      );
      const metaDataFilePath = `${this.plugin.settings.folder}/${metaDataFileName}`;
      yield this.createMetaDataFile(metaDataFilePath, file);
    });
  }
  generateMetaDataFileName(file) {
    const metaDataFileName = `${this.plugin.formatter.format(
      this.plugin.settings.filenameFormat,
      file.path,
      file.stat.ctime
    )}.md`;
    return metaDataFileName;
  }
  uniquefyMetaDataFileName(metaDataFileName) {
    const metaDataFilePath = (0, import_obsidian3.normalizePath)(
      `${this.plugin.settings.folder}/${metaDataFileName}`
    );
    if (this.app.vault.getAbstractFileByPath(metaDataFilePath)) {
      return `CONFLICT-${(0, import_obsidian3.moment)().format(
        "YYYY-MM-DD-hh-mm-ss"
      )}-${metaDataFileName}`;
    } else {
      return metaDataFileName;
    }
  }
  createMetaDataFile(metaDataFilePath, binaryFile) {
    return __async(this, null, function* () {
      const templateContent = yield this.fetchTemplateContent();
      const templaterPlugin = yield this.getTemplaterPlugin();
      if (!(this.plugin.settings.useTemplater && templaterPlugin)) {
        this.app.vault.create(
          metaDataFilePath,
          this.plugin.formatter.format(
            templateContent,
            binaryFile.path,
            binaryFile.stat.ctime
          )
        );
      } else {
        const targetFile = yield this.app.vault.create(metaDataFilePath, "");
        try {
          const content = yield templaterPlugin.templater.parse_template(
            { target_file: targetFile, run_mode: 4 },
            this.plugin.formatter.format(
              templateContent,
              binaryFile.path,
              binaryFile.stat.ctime
            )
          );
          this.app.vault.modify(targetFile, content);
        } catch (err) {
          new import_obsidian3.Notice(
            "ERROR in Binary File Manager Plugin: failed to connect to Templater. Your Templater version may not be supported"
          );
          console.log(err);
        }
      }
    });
  }
  fetchTemplateContent() {
    return __async(this, null, function* () {
      if (this.plugin.settings.templatePath === "") {
        return DEFAULT_TEMPLATE_CONTENT;
      }
      const templateFile = yield retry(
        () => {
          return this.app.vault.getAbstractFileByPath(
            this.plugin.settings.templatePath
          );
        },
        TIMEOUT_MILLISECOND,
        RETRY_NUMBER,
        (abstractFile) => abstractFile !== null
      );
      if (!(templateFile instanceof import_obsidian3.TFile)) {
        const msg = `Template file ${this.plugin.settings.templatePath} is invalid`;
        console.log(msg);
        new import_obsidian3.Notice(msg);
        return DEFAULT_TEMPLATE_CONTENT;
      }
      return yield this.app.vault.read(templateFile);
    });
  }
  getTemplaterPlugin() {
    return __async(this, null, function* () {
      const app = this.app;
      return yield retry(
        () => {
          return app.plugins.plugins[TEMPLATER_PLUGIN_NAME];
        },
        TIMEOUT_MILLISECOND,
        RETRY_NUMBER
      );
    });
  }
  findUnlinkedBinaries() {
    const unlinkedBinaries = [];
    const linkedPaths = /* @__PURE__ */ new Set();
    Object.values(this.app.metadataCache.resolvedLinks).forEach((links) => {
      Object.keys(links).forEach((dest) => {
        linkedPaths.add(dest);
      });
    });
    this.app.vault.getFiles().forEach((file) => {
      const isUnlinkedBinary = !linkedPaths.has(file.path) && this.plugin.fileExtensionManager.verify(file.path);
      if (isUnlinkedBinary) {
        unlinkedBinaries.push(file);
      }
    });
    return unlinkedBinaries;
  }
};

// src/Setting.ts
var import_obsidian6 = require("obsidian");

// src/suggesters/FileSuggester.ts
var import_obsidian4 = require("obsidian");
var FileSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian4.TFile && file.extension === "md" && file.path.toLowerCase().contains(lowerCaseInputStr)) {
        files.push(file);
      }
    });
    return files;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.setValue(file.path);
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/suggesters/FolderSuggester.ts
var import_obsidian5 = require("obsidian");
var FolderSuggest = class extends import_obsidian5.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian5.TFolder && folder.path.toLowerCase().contains(lowerCaseInputStr)) {
        folders.push(folder);
      }
    });
    return folders;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.setValue(file.path);
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/Setting.ts
var BinaryFileManagerSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Enable auto detection").setDesc("Detects new binary files and create metadata automatically.").addToggle((component) => {
      component.setValue(this.plugin.settings.autoDetection).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.autoDetection = value;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian6.Setting(containerEl).setName("New file location").setDesc("New metadata file will be placed here").addSearch((component) => {
      new FolderSuggest(this.app, component.inputEl);
      component.setPlaceholder("Example: folder1/folder2").setValue(this.plugin.settings.folder).onChange((newFolder) => {
        this.plugin.settings.folder = newFolder;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("File name format").then((setting) => {
      setting.addText((component) => {
        component.setValue(this.plugin.settings.filenameFormat).onChange((input) => {
          const newFormat = input.trim().replace(/\.md$/, "");
          if (newFormat === "") {
            new import_obsidian6.Notice("File name format must not be blanck");
            return;
          }
          const sampleFileName2 = this.plugin.formatter.format(
            newFormat,
            "folder/sample.png",
            import_obsidian6.moment.now()
          );
          this.displaySampleFileNameDesc(setting.descEl, sampleFileName2);
          const { valid } = validFileName(sampleFileName2);
          if (!valid) {
            return;
          }
          this.plugin.settings.filenameFormat = newFormat;
          this.plugin.saveSettings();
        });
        const sampleFileName = this.plugin.formatter.format(
          this.plugin.settings.filenameFormat,
          "folder/sample.png",
          import_obsidian6.moment.now()
        );
        this.displaySampleFileNameDesc(setting.descEl, sampleFileName);
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Template file location").addSearch((component) => {
      new FileSuggest(this.app, component.inputEl);
      component.setPlaceholder("Example: folder1/note").setValue(this.plugin.settings.templatePath).onChange((newTemplateFile) => {
        this.plugin.settings.templatePath = newTemplateFile;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Use Templater").addToggle((component) => __async(this, null, function* () {
      component.setValue(this.plugin.settings.useTemplater).onChange((value) => {
        this.plugin.settings.useTemplater = value;
        this.plugin.saveSettings();
      });
    }));
    let extensionToBeAdded;
    new import_obsidian6.Setting(containerEl).setName("Extension to be watched").addText(
      (text) => text.setPlaceholder("Example: pdf").onChange((value) => {
        extensionToBeAdded = value.trim().replace(/^\./, "");
      })
    ).addButton((cb) => {
      cb.setButtonText("Add").onClick(() => __async(this, null, function* () {
        if (extensionToBeAdded === "md") {
          new import_obsidian6.Notice('extension "md" is prohibited');
          return;
        }
        if (this.plugin.fileExtensionManager.has(extensionToBeAdded)) {
          new import_obsidian6.Notice(`${extensionToBeAdded} is already registered`);
          return;
        }
        this.plugin.fileExtensionManager.add(extensionToBeAdded);
        this.plugin.settings.extensions.push(extensionToBeAdded);
        yield this.plugin.saveSettings();
        this.display();
      }));
    });
    this.plugin.settings.extensions.forEach((ext) => {
      new import_obsidian6.Setting(containerEl).setName(ext).addExtraButton((cb) => {
        cb.setIcon("cross").onClick(() => __async(this, null, function* () {
          this.plugin.fileExtensionManager.delete(ext);
          this.plugin.settings.extensions = this.plugin.fileExtensionManager.toArray();
          yield this.plugin.saveSettings();
          this.display();
        }));
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Forget all binary files").setDesc(
      "Binary File Manager remembers binary files for which it has created metadata. If it forgets, then it recognizes all binary files as newly created files and tries to create their metadata again."
    ).addButton((component) => {
      component.setButtonText("Forget").setWarning().onClick(() => {
        new ForgetAllModal(this.app, this.plugin).open();
      });
    });
  }
  displaySampleFileNameDesc(descEl, sampleFileName) {
    descEl.empty();
    descEl.appendChild(
      createFragment((fragment) => {
        fragment.appendText("For more syntax, refer to ");
        fragment.createEl("a", {
          href: "https://github.com/qawatake/obsidian-binary-file-manager-plugin#format-syntax",
          text: "format reference"
        });
        fragment.createEl("br");
        fragment.appendText("Your current syntax looks like this: ");
        fragment.createEl("b", {
          text: sampleFileName
        });
        const { valid, included } = validFileName(sampleFileName);
        if (!valid && included !== void 0) {
          fragment.createEl("br");
          const msgEl = fragment.createEl("span");
          msgEl.appendText(`${included} must not be included`);
          msgEl.addClass("binary-file-manager-text-error");
        }
      })
    );
  }
};
var ForgetAllModal = class extends import_obsidian6.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Forget all");
    contentEl.createEl("p", {
      text: "Are you sure? You cannot undo this action."
    }).addClass("mod-warning");
    const buttonContainerEl = contentEl.createEl("div");
    buttonContainerEl.addClass("modal-button-container");
    new import_obsidian6.ButtonComponent(buttonContainerEl).setButtonText("Forget").setWarning().onClick(() => __async(this, null, function* () {
      this.plugin.fileListAdapter.deleteAll();
      yield this.plugin.fileListAdapter.save();
      new import_obsidian6.Notice("Binary File Manager forgets all!");
      this.close();
    }));
    new import_obsidian6.ButtonComponent(buttonContainerEl).setButtonText("Cancel").onClick(() => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var import_obsidian7 = require("obsidian");
var DEFAULT_SETTINGS = {
  autoDetection: false,
  extensions: [
    "png",
    "jpg",
    "jpeg",
    "gif",
    "bmp",
    "svg",
    "mp3",
    "webm",
    "wav",
    "m4a",
    "ogg",
    "3gp",
    "flac",
    "mp4",
    "webm",
    "ogv",
    "pdf"
  ],
  folder: "/",
  filenameFormat: "INFO_{{NAME}}_{{EXTENSION:UP}}",
  templatePath: "",
  useTemplater: false
};
var BinaryFileManagerPlugin = class extends import_obsidian7.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.formatter = new Formatter(this.app, this);
      this.fileExtensionManager = new FileExtensionManager(this);
      this.fileListAdapter = yield new FileListAdapter(this.app, this).load();
      this.metaDataGenerator = new MetaDataGenerator(this.app, this);
      this.registerEvent(
        this.app.vault.on("create", (file) => __async(this, null, function* () {
          if (!this.settings.autoDetection) {
            return;
          }
          if (!(yield this.metaDataGenerator.shouldCreateMetaDataFile(file))) {
            return;
          }
          yield this.metaDataGenerator.create(file);
          new import_obsidian7.Notice(`Metadata file of ${file.name} is created.`);
          this.fileListAdapter.add(file.path);
          yield this.fileListAdapter.save();
        }))
      );
      this.registerEvent(
        this.app.vault.on("delete", (file) => __async(this, null, function* () {
          if (!this.fileListAdapter.has(file.path)) {
            return;
          }
          this.fileListAdapter.delete(file.path);
          yield this.fileListAdapter.save();
        }))
      );
      this.addCommand({
        id: "binary-file-manager-manual-detection",
        name: "Create metadata for binary files",
        callback: () => __async(this, null, function* () {
          const promises = [];
          const allFiles = this.app.vault.getFiles();
          for (const file of allFiles) {
            if (!(yield this.metaDataGenerator.shouldCreateMetaDataFile(file))) {
              continue;
            }
            promises.push(
              this.metaDataGenerator.create(file).then(() => {
                new import_obsidian7.Notice(`Metadata file of ${file.name} is created.`);
                this.fileListAdapter.add(file.path);
              })
            );
          }
          yield Promise.all(promises);
          this.fileListAdapter.save();
        })
      });
      this.addCommand({
        id: "binary-file-manager-detect-unlinked-binary-files",
        name: "Create metadata for unlinked binary files",
        callback: () => __async(this, null, function* () {
          const promises = [];
          const unlinkedFiles = this.metaDataGenerator.findUnlinkedBinaries();
          unlinkedFiles.forEach((file) => {
            promises.push(
              this.metaDataGenerator.create(file).then(() => {
                new import_obsidian7.Notice(`Metadata file of ${file.name} is created.`);
                this.fileListAdapter.add(file.path);
              })
            );
          });
          yield Promise.all(promises);
          this.fileListAdapter.save();
        })
      });
      this.addSettingTab(new BinaryFileManagerSettingTab(this.app, this));
    });
  }
  // onunload() {}
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};

/* nosourcemap */